-- ENABLE ROW LEVEL SECURITY FOR ALL PUBLIC TABLES
-- This resolves the Supabase Security Advisor alerts and secures the PostgREST API.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrganizationMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IntegrationCredential" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Client" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FinancialRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PNLMapping" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PNLValue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BudgetMapping" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BudgetValue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RateLimit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HandshakeCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomSubHead" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Device" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PairingCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrialBalanceUpload" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RawLedgerRecord" ENABLE ROW LEVEL SECURITY;

-- Note: No public policies are created. This denies all access via the 
-- Supabase REST API (PostgREST), which is ideal since Prisma handles 
-- all data access from the server side.
